# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('B', 'Big creature'), ('M', 'Medium creature'), ('S', 'Small creature')], default='Big creature', max_length=2)),
                ('dead', models.BooleanField(default=False)),
                ('date_of_dead', models.DateTimeField(null=True)),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon'), ('R', 'Rodent'), ('I', 'Insect'), ('M', 'Mamal'), ('R', 'Reptile')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('HU', 'Human'), ('AS', 'Asgardian'), ('FG', 'Frost Giant'), ('H', 'Hamser'), ('R', 'Rat'), ('W', 'Wasp'), ('A', 'Ant'), ('M', 'Mosquito'), ('C', 'Crocodile'), ('S', 'Snake'), ('D', 'Dog'), ('C', 'Cat'), ('RD', 'Red dragon'), ('BD', 'Black dragon'), ('E', 'Ent'), ('T', 'Treebeard'), ('LI', 'Lion')], default='Human', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='heroes.Hero'),
        ),
        migrations.AddField(
            model_name='battle',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='heroes.Hero'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='heroes.Hero'),
        ),
    ]
