# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('date_of_death', models.DateTimeField(null=True)),
                ('wins', models.BigIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('wins', models.BigIntegerField(default=0)),
                ('defeats', models.BigIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.BooleanField(default=False)),
                ('date_of_death', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HeroGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HeroKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breed', to='heroes.HeroGroup'),
        ),
        migrations.AddField(
            model_name='hero',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='heroes.HeroGroup'),
        ),
        migrations.AddField(
            model_name='hero',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kind', to='heroes.HeroKind'),
        ),
        migrations.AddField(
            model_name='battle',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='heroes.Hero'),
        ),
        migrations.AddField(
            model_name='battle',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='heroes.Hero'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='heroes.Hero'),
        ),
    ]
