# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('date_of_death', models.DateTimeField(null=True)),
                ('wins', models.BigIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='heroes.Hero'),
        ),
    ]
