# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_plant',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('E', 'Ent'), ('T', 'Treebeard')], default='Ent', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('RD', 'Red dragon'), ('BD', 'Black dragon')], default='Red dragon', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.CreateModel(
            name='Humanoid',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('HU', 'Human'), ('AS', 'Asgardian'), ('FG', 'Frost Giant')], default='Human', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('W', 'Wasp'), ('A', 'Ant'), ('M', 'Mosquito')], default='Wasp', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.CreateModel(
            name='Mamal',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], default='Cats', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('C', 'Crocodile'), ('S', 'Snake')], default='Crocodile', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.CreateModel(
            name='Rodent',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heroes.Hero')),
                ('group', models.CharField(choices=[('HU', 'Humanoid'), ('BP', 'Big plant'), ('DR', 'Dragon')], default='Humanoid', max_length=2)),
                ('breed', models.CharField(choices=[('H', 'Hamser'), ('R', 'Rat')], default='Hamser', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('heroes.hero',),
        ),
        migrations.AlterField(
            model_name='hero',
            name='kind',
            field=models.CharField(choices=[('B', 'Big creature'), ('M', 'Medium creature'), ('S', 'Small creature')], default='Big creature', max_length=2),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
