# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20180618_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='date_of_dead',
            field=models.DateTimeField(null=True),
        ),
    ]
